# Generated by Django 4.1.4 on 2022-12-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_userid', models.CharField(default='', max_length=10)),
                ('patient_password', models.CharField(default='', max_length=10)),
                ('patient_name', models.CharField(default='', max_length=10)),
                ('patient_birth', models.DateField(default='')),
                ('patient_phone_number', models.CharField(default='', max_length=20)),
                ('patient_email', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
