# Generated by Django 4.1.3 on 2022-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=10)),
                ("patient_password", models.CharField(max_length=10)),
                ("patient_birth", models.DateField(blank=True, null=True)),
                (
                    "patient_email",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
