# Generated by Django 4.1.4 on 2022-12-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_userid',
        ),
    ]
