# Generated by Django 4.1.4 on 2022-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(blank=True, max_length=50, null=True)),
                ('hospital_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital_department', models.CharField(max_length=10)),
            ],
        ),
    ]
