# Generated by Django 3.2 on 2022-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_state',
            field=models.CharField(choices=[('P', 'PENDING AOOROVED'), ('A', 'APPROVED'), ('R', 'REJECTED'), ('C', 'COMPLETE')], default='', max_length=1),
        ),
    ]
