# Generated by Django 3.2 on 2022-12-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_reservation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_state',
            field=models.CharField(choices=[('P', 'PENDING AOOROVED'), ('A', 'APPROVED'), ('R', 'REJECTED'), ('C', 'COMPLETE')], default='P', max_length=1),
        ),
    ]
