# Generated by Django 3.2 on 2022-12-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_reservation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_state',
        ),
    ]
